### ISSUE TITLE
Incorporate DbgHelp

### ISSUE THREAD

**Issue by klemens-morgenstern** [boostorg/winapi#10]
I need a few functions from DbgHelp.h for an extension of boost.DLL, would this fit into this library? It's not the winapi strictly speaking, but it's so heavily dependent on that, that I'd like to add it here as soon as it's tested.

**Comment by Lastique** [comment]
No, I think this submodule is not the right place for it.

Why don't you just #include DbgHelp.h in Boost.DLL?

**Comment by klemens-morgenstern** [comment]
Because it incorporates all this Winapi stuff, which I want to avoid for a header-only library
