### ISSUE TITLE
"ISO C++ prohibits anonymous structs" warning in system.hpp

### ISSUE THREAD

**Issue by pdimov** [boostorg/winapi#64]
The Pool tests use `-Werror` and fail under MinGW with

```
..\../boost/winapi/system.hpp:52:9: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
         } DUMMYSTRUCTNAME;
         ^
```

The member is given a dummy name, but the `struct` itself isn't.

**Comment by Lastique** [comment]
Duplicates https://github.com/boostorg/winapi/issues/62.
