### ISSUE TITLE
warning on duplicate macro definitions

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/winapi#69]
I believe these are caused by Boost.WinAPI

http://www.boost.org/development/tests/develop/output/teeks99-09-f-win2016-64on64-beast-msvc-14-0-warnings.html#accept

**Comment by Lastique** [comment]
Yes, this will be fixed when all dependent libraries are ported to Boost.WinAPI new macros in master, which will happen after 1.67 is out.
