### ISSUE TITLE
Multiple Errors -  C28251 in VS 2022 (17.0.3) - v143

### ISSUE THREAD

**Issue by Reet-Kaur** [boostorg/winapi#89]
Hi, 

I am trying to build my projects in VS2022 (17.0.3) with the latest build tools in Release(x64) mode. I get the following errors -

![image](https://user-images.githubusercontent.com/40193051/146638355-99d4c161-f512-4de5-9dd2-9624bc924fb7.png)
![image](https://user-images.githubusercontent.com/40193051/146638361-229f4a7c-71ac-4bed-9548-b77ad986675f.png)

Other relevant settings -
Disable language Extensions - set to NO
![image](https://user-images.githubusercontent.com/40193051/146638418-0696230c-32b8-4087-b66e-361474951b28.png)

The projects build fine in Debug mode, so I wonder if upgrading to a more latest Boost version would  help in this case.

Thanks in anticipation!

**Comment by Lastique** [comment]
Duplicates https://github.com/boostorg/winapi/issues/78.
