### ISSUE TITLE
Add wrappers for Windows GDI functions

### ISSUE THREAD

**Issue by AndreyHa** [boostorg/winapi#93]
References
[Win32 GDI on learn.microsoft.com](https://learn.microsoft.com/en-us/windows/win32/gdi/windows-gdi)

**Comment by Lastique** [comment]
I don't think any Boost libraries use GDI, so there seems to be no users for wrappers in Boost.WinAPI.

BTW, as far as I know, GDI is a legacy API, so it seems unlikely that new users will appear.
